services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ${DATA_PATH}:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: ${DB}
      CLICKHOUSE_PASSWORD: ${PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: 4
