services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: ${VERSION}
      DISK_SIZE: ${DISK_SIZE}
      RAM_SIZE: ${RAM_SIZE}
      CPU_CORES: ${CPU_CORES}
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ${DATA_PATH}:/storage
    stop_grace_period: 2m