---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${DATA_PATH}/appdata:/config
      - ${DATA_PATH}/downloads:/downloads #optional
      - ${MOUNT_PATH}:${MOUNT_PATH}
    ports:
      - 28080:8080
      - 26881:6881
      - 26881:6881/udp
    restart: unless-stopped

