services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    network_mode: host
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
      - DISABLE_IPV6=false
      - NPM_PORT=81    # 将管理端口改为 82
    volumes:
      - ./data/data:/data
      - ./data/letsencrypt:/etc/letsencrypt
